# using CJB_BIN from ~/.bashrc
. $CJB_BIN/dotfiles/bash/env
. $CJB_BIN/dotfiles/bash/config
. $CJB_BIN/dotfiles/bash/aliases
. $CJB_BIN/dotfiles/bash/inputrc
. $CJB_BIN/git-completion.bash









# Casey's old stuff (pre-peepcode)



#export EDITOR=/Applications/Emacs.app/Contents/MacOS/bin/emacsclient

#source ~/.git-completion.bash
