#!/bin/bash


export PATH="\
/usr/local/bin:\
/usr/local/sbin:\
/usr/bin:\
/bin:\
/usr/sbin:\
/sbin:\
$CJB_BIN/scripts:\
"

export EDITOR="vim"
export NODE_PATH="/usr/local/lib/node_modules"

# no .pyc files
export PYTHONDONTWRITEBYTECODE=1

# lots of history, and append it to histfile instead of overwriting
export HISTSIZE=100000
shopt -s histappend

# enable color in 'ls' output, even when piping to 'less'
export CLICOLOR=1
export CLICOLOR_FORCE=1

##########
# ALIASES
##########

# git aliases
alias g="git status"
alias gfg="git fetch github"
alias gitc="git diff --cached"

# open this project on github
alias gho="github_open.sh"

# merge github version of this branch with local
alias gm="git_merge_current_remote_branch"

# spelling is hard
alias gtci="gitc"
alias gtic="gitc"

# grep stuff
alias grep="grep --color=auto -E --exclude=tags"
alias jsgrep='find . -type f -and \( -name "*.coffee" -or -name "*.js" -or -name "*.hbs" \) -and -not -path "*node_modules*" -print0 | xargs -0 grep'
alias pygrep='find . -type f -and -name "*.py" -and -not -path "*migrations*" -print0 | xargs -0 grep'

# ls better
alias ls="ls -FGC"
alias l="ls -lh"
alias ll="l | less -R"
alias la="l -a"
alias lal="la | less -R"

# random helpers
alias die_pyc="find . -name '*.pyc' -delete"
alias e="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n"
alias j="jobs"
alias json="python -m json.tool"
alias msp="./manage.py shell_plus"
alias p="pbcopy"
alias py="python"
alias scr="screen -r"
alias types="find . -type f -exec basename {} \; | rev | cut -d '.' -f 1 | rev | sort | uniq" # list all filetypes in this and child directories
alias x="xargs"


#########
# Prompt
#########

NO_COLOR='\e[0m'
EYELLOW='\e[1;33m'
PS1="\n\u:\w \[$EYELLOW\]\$(vcprompt)\[$NO_COLOR\] \n$ "


source $CJB_BIN/scripts/git-completion.bash
source $CJB_BIN/scripts/random_functions.sh
source $CJB_BIN/local_bash_config

