#!/bin/bash

export PATH="\
/usr/local/bin:\
/usr/local/sbin:\
/usr/bin:\
/bin:\
/usr/sbin:\
/sbin:\
~/global_npm/bin:\
$CJB_BIN/scripts:\
"

export EDITOR="vim"

# lots of history, and append it to histfile instead of overwriting
export HISTSIZE=100000
shopt -s histappend

# enable color in 'ls' output, even when piping to 'less'
export CLICOLOR=1
export CLICOLOR_FORCE=1

##########
# ALIASES
##########

# git aliases
alias g="git status"
alias gfg="git fetch github"
alias gitc="git diff --cached"

# open this project on github
alias gho="github_open.sh"

# merge github version of this branch with local
alias gm="git_merge_current_remote_branch"

# spelling is hard
alias gtci="gitc"
alias gtic="gitc"

# grep stuff
alias grep="grep --color=auto -E --exclude=tags"
alias jsgrep='find . -type f -and \( -name "*.coffee" -or -name "*.js" -or -name "*.hbs" \) -and -not -path "*node_modules*" -print0 | xargs -0 grep'
alias pygrep='find . -type f -and -name "*.py" -and -not -path "*migrations*" -print0 | xargs -0 grep'
alias htmlgrep='find . -type f -and -name "*.html" -print0 | xargs -0 grep'
alias cgrep='find . -type f -and -name "*.c" -or -name "*.h" -print0 | xargs -0 grep'

# ls better
alias ls="ls -FGC"
alias l="ls -lh"
alias ll="l | less -R"
alias la="l -a"
alias lal="la | less -R"

# random helpers
alias die_pyc="find . -name '*.pyc' -delete ; find . -type d -name '__pycache__' -delete"
alias e="/Applications/Emacs.app/Contents/MacOS/bin/emacsclient -n"
alias j="jobs"
alias json="python -m json.tool"
alias msp="./manage.py shell_plus"
alias n="cd ~/Dropbox/notes"
alias p="pbcopy"
alias psh="pushd ~"
alias py="python"
alias p3m="python3 manage.py"
alias scr="screen -r"
alias types="find . -type f -exec basename {} \; | rev | cut -d '.' -f 1 | rev | sort | uniq" # list all filetypes in this and child directories
alias vi="echo 'pls type all three letters of vim'"
alias vv=". venv/bin/activate"
alias x="xargs"


#########
# Prompt
#########

number_of_running_jobs() {
  NUM=`jobs | wc -l | awk '{print $1}'`
  if [ "$NUM" = "0" ] ; then
    echo ""
  else
    echo "[$NUM]"
  fi
}

NO_COLOR='\e[0m'
YELLOW='\e[1;33m'
BLUE='\e[1;34m'
CYAN='\e[1;36m'
PS1="\n$BLUE\h $CYAN\u $NO_COLOR\w $YELLOW \$(number_of_running_jobs) $NO_COLOR \n$ "


source $CJB_BIN/scripts/git-completion.bash
source $CJB_BIN/scripts/random_functions.sh
source $CJB_BIN/local_bash_config

