#!/bin/bash

set -e

if [ -f ~/.notesrc ] ; then
  source ~/.notesrc
fi

if [ -z "$NOTES_DIR" ] ; then
  NOTES_DIR=~/notes
fi

echo "Notes home is $NOTES_DIR"

SEARCH_STRING="$*"

main() {
  if [ -z "$SEARCH_STRING" ] ; then
    pick_file
  else
    search_notes
  fi
}

pick_file() {
  picked_file=$(
    all_notes_files |
    strip_full_path |
    present_filter |
    reattach_full_path
  )
  output_picked_file
}

search_notes() {
  picked_file=$(
    all_notes_files0 |
    search |
    strip_full_path |
    present_filter |
    filename_from_search_result |
    reattach_full_path
  )
  output_picked_file
}

all_notes_files() {
  find "$NOTES_DIR" -not -path "*.git*" -and -type f
}

all_notes_files0() {
  find "$NOTES_DIR" -not -path "*.git*" -and -type f -print0
}

search() {
  xargs -0 grep -inE "$SEARCH_STRING"
}

filename_from_search_result() {
  cut -d ':' -f 1
}

strip_full_path() {
  sed -E "s#^$NOTES_DIR(.*)#\1#"
}

present_filter() {
  selecta 2>/dev/null
}

reattach_full_path() {
  echo "$NOTES_DIR$(cat -)"
}

output_picked_file() {
  if [ -f "$picked_file" ] ; then
    echo
    cat "$picked_file"
  fi
  echo
}

main
